/*******************************************************************************
 * Copyright 2017 Samsung Electronics All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *******************************************************************************/

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Event.proto

package ezmq

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Id               *string    `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Created          *int64     `protobuf:"varint,2,req,name=created" json:"created,omitempty"`
	Modified         *int64     `protobuf:"varint,3,req,name=modified" json:"modified,omitempty"`
	Origin           *int64     `protobuf:"varint,4,req,name=origin" json:"origin,omitempty"`
	Pushed           *int64     `protobuf:"varint,5,req,name=pushed" json:"pushed,omitempty"`
	Device           *string    `protobuf:"bytes,6,req,name=device" json:"device,omitempty"`
	Reading          []*Reading `protobuf:"bytes,7,rep,name=reading" json:"reading,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

//This method is added specifically for ezmq message.
func (m Event) GetContentType() EZMQContentType {
	return EZMQ_CONTENT_TYPE_PROTOBUF
}

func (m *Event) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Event) GetCreated() int64 {
	if m != nil && m.Created != nil {
		return *m.Created
	}
	return 0
}

func (m *Event) GetModified() int64 {
	if m != nil && m.Modified != nil {
		return *m.Modified
	}
	return 0
}

func (m *Event) GetOrigin() int64 {
	if m != nil && m.Origin != nil {
		return *m.Origin
	}
	return 0
}

func (m *Event) GetPushed() int64 {
	if m != nil && m.Pushed != nil {
		return *m.Pushed
	}
	return 0
}

func (m *Event) GetDevice() string {
	if m != nil && m.Device != nil {
		return *m.Device
	}
	return ""
}

func (m *Event) GetReading() []*Reading {
	if m != nil {
		return m.Reading
	}
	return nil
}

type Reading struct {
	Id               *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Created          *int64  `protobuf:"varint,2,req,name=created" json:"created,omitempty"`
	Modified         *int64  `protobuf:"varint,3,req,name=modified" json:"modified,omitempty"`
	Origin           *int64  `protobuf:"varint,4,req,name=origin" json:"origin,omitempty"`
	Pushed           *int64  `protobuf:"varint,5,req,name=pushed" json:"pushed,omitempty"`
	Name             *string `protobuf:"bytes,6,req,name=name" json:"name,omitempty"`
	Value            *string `protobuf:"bytes,7,req,name=value" json:"value,omitempty"`
	Device           *string `protobuf:"bytes,8,req,name=device" json:"device,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Reading) Reset()                    { *m = Reading{} }
func (m *Reading) String() string            { return proto.CompactTextString(m) }
func (*Reading) ProtoMessage()               {}
func (*Reading) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Reading) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Reading) GetCreated() int64 {
	if m != nil && m.Created != nil {
		return *m.Created
	}
	return 0
}

func (m *Reading) GetModified() int64 {
	if m != nil && m.Modified != nil {
		return *m.Modified
	}
	return 0
}

func (m *Reading) GetOrigin() int64 {
	if m != nil && m.Origin != nil {
		return *m.Origin
	}
	return 0
}

func (m *Reading) GetPushed() int64 {
	if m != nil && m.Pushed != nil {
		return *m.Pushed
	}
	return 0
}

func (m *Reading) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Reading) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func (m *Reading) GetDevice() string {
	if m != nil && m.Device != nil {
		return *m.Device
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "ezmq.Event")
	proto.RegisterType((*Reading)(nil), "ezmq.Reading")
}

func init() { proto.RegisterFile("Event.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xd9, 0xb4, 0xdd, 0xac, 0xb3, 0xb8, 0x87, 0x20, 0x32, 0x78, 0x2a, 0xeb, 0xc1, 0x9e,
	0x7a, 0x10, 0x7c, 0x81, 0x85, 0x3d, 0x0a, 0xda, 0xa3, 0xb7, 0xba, 0x33, 0xad, 0x01, 0x9b, 0xac,
	0xb1, 0x2d, 0xea, 0xc3, 0x09, 0xbe, 0x99, 0x24, 0x69, 0x65, 0xdf, 0xc0, 0x5b, 0xbe, 0xef, 0x3f,
	0x64, 0x7e, 0x7e, 0x58, 0xef, 0x47, 0x36, 0x7d, 0x79, 0x74, 0xb6, 0xb7, 0x2a, 0xe5, 0xaf, 0xee,
	0x6d, 0xfb, 0xbd, 0x80, 0x2c, 0x58, 0xb5, 0x01, 0xa1, 0x09, 0x17, 0xb9, 0x28, 0xce, 0x2a, 0xa1,
	0x49, 0x21, 0xc8, 0x83, 0xe3, 0xba, 0x67, 0x42, 0x91, 0x8b, 0x22, 0xa9, 0x66, 0x54, 0x57, 0xb0,
	0xea, 0x2c, 0xe9, 0x46, 0x33, 0x61, 0x12, 0xa2, 0x3f, 0x56, 0x97, 0xb0, 0xb4, 0x4e, 0xb7, 0xda,
	0x60, 0x1a, 0x92, 0x89, 0xbc, 0x3f, 0x0e, 0xef, 0x2f, 0x4c, 0x98, 0x45, 0x1f, 0xc9, 0x7b, 0xe2,
	0x51, 0x1f, 0x18, 0x97, 0xe1, 0xe7, 0x89, 0xd4, 0x0d, 0x48, 0xc7, 0x35, 0x69, 0xd3, 0xa2, 0xcc,
	0x93, 0x62, 0x7d, 0x7b, 0x5e, 0xfa, 0x7b, 0xcb, 0x2a, 0xca, 0x6a, 0x4e, 0xb7, 0x3f, 0x0b, 0x90,
	0x93, 0xfc, 0xa7, 0x0a, 0x0a, 0x52, 0x53, 0x77, 0x73, 0x81, 0xf0, 0x56, 0x17, 0x90, 0x8d, 0xf5,
	0xeb, 0xc0, 0x28, 0x83, 0x8c, 0x70, 0x52, 0x76, 0x75, 0x5a, 0x76, 0x77, 0x07, 0xd7, 0xd6, 0xb5,
	0x25, 0x53, 0xcb, 0x1f, 0x8d, 0x1d, 0x0c, 0xb9, 0xcf, 0xd8, 0x36, 0x2c, 0xf5, 0x3c, 0x34, 0xec,
	0x17, 0xda, 0x6d, 0xf6, 0x4f, 0xf7, 0x8f, 0x0f, 0x5e, 0x85, 0xc5, 0x7e, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x51, 0x52, 0x64, 0x9d, 0xcf, 0x01, 0x00, 0x00,
}
