// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Event.proto

package ezmq

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Id               *string    `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Created          *int64     `protobuf:"varint,2,req,name=created" json:"created,omitempty"`
	Modified         *int64     `protobuf:"varint,3,req,name=modified" json:"modified,omitempty"`
	Origin           *int64     `protobuf:"varint,4,req,name=origin" json:"origin,omitempty"`
	Pushed           *int64     `protobuf:"varint,5,req,name=pushed" json:"pushed,omitempty"`
	Device           *string    `protobuf:"bytes,6,req,name=device" json:"device,omitempty"`
	Reading          []*Reading `protobuf:"bytes,7,rep,name=reading" json:"reading,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Event) GetCreated() int64 {
	if m != nil && m.Created != nil {
		return *m.Created
	}
	return 0
}

func (m *Event) GetModified() int64 {
	if m != nil && m.Modified != nil {
		return *m.Modified
	}
	return 0
}

func (m *Event) GetOrigin() int64 {
	if m != nil && m.Origin != nil {
		return *m.Origin
	}
	return 0
}

func (m *Event) GetPushed() int64 {
	if m != nil && m.Pushed != nil {
		return *m.Pushed
	}
	return 0
}

func (m *Event) GetDevice() string {
	if m != nil && m.Device != nil {
		return *m.Device
	}
	return ""
}

func (m *Event) GetReading() []*Reading {
	if m != nil {
		return m.Reading
	}
	return nil
}

type Reading struct {
	Id               *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Created          *int64  `protobuf:"varint,2,req,name=created" json:"created,omitempty"`
	Modified         *int64  `protobuf:"varint,3,req,name=modified" json:"modified,omitempty"`
	Origin           *int64  `protobuf:"varint,4,req,name=origin" json:"origin,omitempty"`
	Pushed           *int64  `protobuf:"varint,5,req,name=pushed" json:"pushed,omitempty"`
	Name             *string `protobuf:"bytes,6,req,name=name" json:"name,omitempty"`
	Value            *string `protobuf:"bytes,7,req,name=value" json:"value,omitempty"`
	Device           *string `protobuf:"bytes,8,req,name=device" json:"device,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Reading) Reset()                    { *m = Reading{} }
func (m *Reading) String() string            { return proto.CompactTextString(m) }
func (*Reading) ProtoMessage()               {}
func (*Reading) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Reading) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Reading) GetCreated() int64 {
	if m != nil && m.Created != nil {
		return *m.Created
	}
	return 0
}

func (m *Reading) GetModified() int64 {
	if m != nil && m.Modified != nil {
		return *m.Modified
	}
	return 0
}

func (m *Reading) GetOrigin() int64 {
	if m != nil && m.Origin != nil {
		return *m.Origin
	}
	return 0
}

func (m *Reading) GetPushed() int64 {
	if m != nil && m.Pushed != nil {
		return *m.Pushed
	}
	return 0
}

func (m *Reading) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Reading) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func (m *Reading) GetDevice() string {
	if m != nil && m.Device != nil {
		return *m.Device
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "ezmq.Event")
	proto.RegisterType((*Reading)(nil), "ezmq.Reading")
}

func init() { proto.RegisterFile("Event.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x91, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x55, 0xa7, 0xa9, 0xcb, 0x14, 0x58, 0x58, 0x08, 0x8d, 0x58, 0x45, 0x59, 0xa0, 0xac,
	0xb2, 0x80, 0x1b, 0x54, 0x2a, 0x3b, 0x24, 0x94, 0x1b, 0x84, 0xce, 0x38, 0x58, 0x22, 0x76, 0x65,
	0x92, 0x08, 0x0e, 0xc7, 0x82, 0x9b, 0xa1, 0x4c, 0x12, 0xd4, 0x1b, 0xb0, 0xf3, 0x7b, 0x7f, 0xe1,
	0xf9, 0xfa, 0xb0, 0x3b, 0x0c, 0xec, 0xbb, 0xf2, 0x14, 0x43, 0x17, 0x4c, 0xc2, 0xad, 0xcd, 0xbf,
	0x57, 0x90, 0x8a, 0x34, 0xd7, 0xa0, 0x1c, 0xe1, 0x2a, 0x53, 0xc5, 0x45, 0xa5, 0x1c, 0x19, 0x04,
	0x7d, 0x8c, 0x5c, 0x77, 0x4c, 0xa8, 0x32, 0x55, 0x24, 0xd5, 0x82, 0xe6, 0x0e, 0xb6, 0x6d, 0x20,
	0x67, 0x1d, 0x13, 0x26, 0x12, 0xfd, 0xb1, 0xb9, 0x85, 0x4d, 0x88, 0xae, 0x71, 0x1e, 0xd7, 0x92,
	0xcc, 0x34, 0xfa, 0x53, 0xff, 0xf1, 0xc6, 0x84, 0xe9, 0xe4, 0x27, 0x1a, 0x3d, 0xf1, 0xe0, 0x8e,
	0x8c, 0x1b, 0xf9, 0x79, 0x26, 0x73, 0x0f, 0x3a, 0x72, 0x4d, 0xce, 0x37, 0xa8, 0xb3, 0xa4, 0xd8,
	0x3d, 0x5c, 0x96, 0xdc, 0xda, 0xb2, 0x9a, 0x5c, 0xb5, 0x84, 0xf9, 0xcf, 0x0a, 0xf4, 0x2c, 0xff,
	0xa9, 0x81, 0x81, 0xb5, 0xaf, 0xdb, 0xe5, 0x7e, 0x79, 0x9b, 0x1b, 0x48, 0x87, 0xfa, 0xbd, 0x67,
	0xd4, 0x22, 0x27, 0x38, 0xeb, 0xba, 0x3d, 0xef, 0xba, 0x7f, 0x84, 0x3c, 0xc4, 0xa6, 0x64, 0x6a,
	0xf8, 0xd3, 0x86, 0xde, 0x53, 0xfc, 0x92, 0xb2, 0x32, 0xd3, 0x6b, 0x6f, 0x79, 0xdc, 0x67, 0x7f,
	0x75, 0x78, 0x7e, 0x7a, 0x19, 0x8d, 0xcc, 0xf5, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xad, 0xcc,
	0x5a, 0xcb, 0x01, 0x00, 0x00,
}
